### ISSUE TITLE
How to give size as an argument for comm_scope?

### ISSUE THREAD

**Issue by Palwisha-18** [c3sr/comm_scope#30]
I am trying to run Comm|Scope benchmark but the size range is set to the power of 2 from 8 to 33.

I want to run for one size and looking at the doc, it says use **log2 size** is the argument format.

I am currently trying **_./scope --benchmark_filter=Comm_Memcpy_GPUToGPUPeer --log2=8_** but I am getting an error for log2 arg.

Can you give an example for running the benchmark with a given size only?

**Comment by cwpearson** [comment]
The size is actually encoded in the name of the benchmark - for example, `Comm_MemcpyPeer/2/3/log2(N):18/manual_time`, runs with a transfer size of 2^18. To select certain transfer sizes, you need to use the regex to select the right benchmarks.

A command to list all benchmarks with `18` in the name would be `./scope --benchmark_list_tests --benchmark_filter=".*18.*"`

TO run the benchmarks, remove `--benchmark_list_tests`

**Comment by Palwisha-18** [comment]
It worked! Thank you. :)
