### ISSUE TITLE
How to fix the number of iterations in a given micro-benchmark?

### ISSUE THREAD

**Issue by Palwisha-18** [c3sr/comm_scope#37]
Hi, 

After running any micro-benchmark several times, it is observed that the number of iterations varies. PFA the log for HostToGPU memcpy to what iteration term I am referring to. Is it possible to fix the iterations through the command line?

Benchmark                                                   Time             CPU   **Iterations** UserCounters...
-------------------------------------------------------------------------------------------------------------
Comm_Memcpy_HostToGPU/log2(N):8/manual_time             10165 ns       122345 ns        **76502** bytes=256 bytes_per_second=24.0178M/s cuda_id=0

**Comment by cwpearson** [comment]
Hey @Palwisha-18,

Comm|Scope uses the Google Benchmark library to control the actual benchmarking runs, and their position seems to be that a user usually doesn't actually need to control the number of iterations, so they don't expose it as a command line option.

However, you should be able to modify the benchmark you want to run with [this](https://github.com/google/benchmark/blob/37177a84b7e8d33696ea1e1854513cb0de3b4dc3/include/benchmark/benchmark.h#L861-L867) API where the benchmark is registered, for example, something like:

```c++
benchmark::RegisterBenchmark(...)->Iterations(10);
```

I haven't tried this myself, so let me know if it doesn't work.

For further discussion, see [google/benchmark#370](https://github.com/google/benchmark/issues/370), [373](https://github.com/google/benchmark/pull/373), [google/benchmark#370](https://github.com/google/benchmark/issues/746).

**Comment by Palwisha-18** [comment]
It worked! Thanks!

**Comment by cwpearson** [comment]
Excellent! I saw https://github.com/Palwisha-18/ComScribe, looks like a worthwhile project. That is an area of interest to me, so let me know if you have any more questions.

I also think your colleague @erhant might be interested in https://github.com/cwpearson/stencil for his 3D stencil GPU communication work. He may also want to look at the related paper https://cwpearson.github.io/publication/2020522_pearson_iwapt

Cheers!

**Comment by Palwisha-18** [comment]
Thank you Carl for your feedback on ComScribe. We have a paper in submission for this project and we would  like to share it with you when it gets accepted.
Thanks :)

**Comment by erhant** [comment]
Also thank you very much for your suggestions on my topic! I will be looking into them.
