### ISSUE TITLE
NUMA node boundary benchmarks?

### ISSUE THREAD

**Issue by rlerdorf** [c3sr/comm_scope#41]
Would it be hard to add benchmark tests that cross NUMA node boundaries? Perhaps by creating a shared memory segment from one NUMA node then measure latency and throughput reading and writing to it from another.

**Comment by cwpearson** [comment]
Hi @rlerdorf ,

These benchmarks just have an emphasis on CPU-GPU right now, so I wasn't planning on adding that. If you're interested in CPU-GPU or GPU-GPU across a NUMA node, those are already implemented though!

Carl

**Comment by rlerdorf** [comment]
Yeah, no problem. After a bit more reading I ended up writing my own cpu-cpu libnuma-based benchmark which is quite a bit simpler than what you are solving here.
